-- Zaberman operational database baseline.
-- Target: PostgreSQL 16+.
-- UUID values are UUIDv7 generated by the mobile client or API; the database
-- deliberately has no random UUID default so offline-created identifiers stay stable.

begin;

create schema if not exists zaberman;
set search_path = zaberman, public;

create function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create function reject_append_only_mutation()
returns trigger
language plpgsql
as $$
begin
  raise exception '% is append-only; create a correcting event/version instead', tg_table_name;
end;
$$;

create table branches (
  id uuid primary key,
  code text not null unique,
  name text not null,
  timezone text not null default 'UTC',
  address jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(trim(code)) > 0),
  check (length(trim(name)) > 0)
);

create table app_users (
  id uuid primary key,
  external_subject text not null unique,
  display_name text not null,
  email text,
  status text not null default 'active'
    check (status in ('active', 'suspended', 'disabled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (length(trim(external_subject)) > 0),
  check (email is null or email = lower(email))
);

create unique index app_users_email_uq
  on app_users (lower(email))
  where email is not null;

create table devices (
  id uuid primary key,
  user_id uuid not null references app_users(id),
  branch_id uuid references branches(id),
  platform text not null check (platform in ('android', 'ios', 'web', 'other')),
  device_name text,
  app_version text,
  status text not null default 'active'
    check (status in ('active', 'revoked', 'retired')),
  last_seen_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table roles (
  code text primary key,
  name text not null,
  description text,
  is_system boolean not null default true
);

create table permissions (
  code text primary key,
  description text not null
);

create table role_permissions (
  role_code text not null references roles(code) on delete cascade,
  permission_code text not null references permissions(code) on delete cascade,
  primary key (role_code, permission_code)
);

create table user_branch_roles (
  user_id uuid not null references app_users(id),
  branch_id uuid not null references branches(id),
  role_code text not null references roles(code),
  granted_by_user_id uuid references app_users(id),
  granted_at timestamptz not null default now(),
  valid_until timestamptz,
  primary key (user_id, branch_id, role_code),
  check (valid_until is null or valid_until > granted_at)
);

create table route_runs (
  id uuid primary key,
  source_system text not null,
  external_id text not null,
  branch_id uuid not null references branches(id),
  service_date date not null,
  route_name text,
  status text not null default 'planned'
    check (status in ('planned', 'released', 'in_progress', 'completed', 'cancelled')),
  version integer not null default 1 check (version > 0),
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, external_id)
);

create table orders (
  id uuid primary key,
  source_system text not null,
  external_id text not null,
  order_number text not null,
  movement_type text not null
    check (movement_type in ('local_standard', 'local_same_day', 'interstate', 'interbranch_transfer')),
  title text,
  origin_branch_id uuid references branches(id),
  destination_branch_id uuid references branches(id),
  pickup_address jsonb not null default '{}'::jsonb,
  delivery_address jsonb not null default '{}'::jsonb,
  declared_weight numeric(14,3),
  weight_unit text not null default 'kg' check (weight_unit in ('kg', 'lb')),
  packaging text,
  comments text,
  status text not null default 'open'
    check (status in ('open', 'pickup_in_progress', 'picked_up', 'in_transit', 'delivered', 'cancelled')),
  version integer not null default 1 check (version > 0),
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, external_id),
  unique (source_system, order_number),
  check (declared_weight is null or declared_weight >= 0)
);

create table tasks (
  id uuid primary key,
  source_system text not null,
  external_id text not null,
  order_id uuid not null references orders(id),
  branch_id uuid not null references branches(id),
  route_run_id uuid references route_runs(id),
  route_sequence integer check (route_sequence is null or route_sequence > 0),
  task_type text not null check (task_type in ('pickup', 'dropoff')),
  status text not null default 'assigned'
    check (status in ('assigned', 'in_progress', 'ready_to_close', 'completed', 'failed', 'cancelled')),
  scheduled_at timestamptz,
  completed_at timestamptz,
  assigned_user_id uuid references app_users(id),
  version integer not null default 1 check (version > 0),
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (source_system, external_id),
  check (completed_at is null or completed_at >= created_at)
);

create table vehicles (
  id uuid primary key,
  source_system text,
  external_id text,
  home_branch_id uuid references branches(id),
  vehicle_number text not null unique,
  plate_number text,
  capacity_weight numeric(14,3),
  weight_unit text not null default 'kg' check (weight_unit in ('kg', 'lb')),
  status text not null default 'active'
    check (status in ('active', 'maintenance', 'retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (capacity_weight is null or capacity_weight > 0),
  check ((source_system is null) = (external_id is null))
);

create unique index vehicles_external_uq
  on vehicles (source_system, external_id)
  where source_system is not null;

create table trips (
  id uuid primary key,
  trip_number text not null unique,
  origin_branch_id uuid not null references branches(id),
  destination_branch_id uuid not null references branches(id),
  vehicle_id uuid references vehicles(id),
  status text not null default 'planned'
    check (status in ('planned', 'loading', 'loaded', 'in_transit', 'unloading', 'completed', 'cancelled')),
  expected_manifest_version integer not null default 1 check (expected_manifest_version > 0),
  confirmed_loading_manifest_id uuid,
  confirmed_unloading_manifest_id uuid,
  scheduled_departure_at timestamptz,
  departed_at timestamptz,
  arrived_at timestamptz,
  completed_at timestamptz,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (origin_branch_id <> destination_branch_id),
  check (arrived_at is null or departed_at is null or arrived_at >= departed_at),
  check (completed_at is null or arrived_at is null or completed_at >= arrived_at)
);

-- One row per client/API mutation. Its UUID is the idempotency operationId.
create table command_requests (
  id uuid primary key,
  command_type text not null,
  entity_type text not null,
  entity_id uuid,
  branch_id uuid not null references branches(id),
  actor_user_id uuid not null references app_users(id),
  device_id uuid references devices(id),
  expected_version integer check (expected_version is null or expected_version > 0),
  request_hash text not null,
  request_payload jsonb not null default '{}'::jsonb,
  status text not null default 'received'
    check (status in ('received', 'applied', 'retry', 'conflict', 'rejected')),
  result_payload jsonb,
  error_code text,
  error_message text,
  retryable boolean not null default false,
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  completed_at timestamptz,
  check (completed_at is null or completed_at >= received_at),
  check (status not in ('conflict', 'rejected') or error_code is not null)
);

create table work_operations (
  id uuid primary key,
  operation_type text not null check (operation_type in ('pickup', 'dropoff', 'loading', 'unloading')),
  branch_id uuid not null references branches(id),
  task_id uuid references tasks(id),
  trip_id uuid references trips(id),
  status text not null default 'draft'
    check (status in ('draft', 'in_progress', 'ready_to_close', 'closed', 'reversed')),
  started_by_user_id uuid not null references app_users(id),
  closed_by_user_id uuid references app_users(id),
  started_at timestamptz not null default now(),
  closed_at timestamptz,
  close_command_id uuid references command_requests(id),
  version integer not null default 1 check (version > 0),
  summary_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (operation_type in ('pickup', 'dropoff') and task_id is not null and trip_id is null)
    or
    (operation_type in ('loading', 'unloading') and trip_id is not null and task_id is null)
  ),
  check (closed_at is null or closed_at >= started_at),
  check ((status in ('closed', 'reversed')) = (closed_at is not null))
);

create table cargo_items (
  id uuid primary key,
  order_id uuid not null references orders(id),
  item_number integer not null check (item_number > 0),
  description text not null,
  quantity numeric(14,3) not null default 1 check (quantity > 0),
  unit text not null default 'piece',
  packaging text,
  declared_weight numeric(14,3),
  weight_unit text not null default 'kg' check (weight_unit in ('kg', 'lb')),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, item_number),
  check (declared_weight is null or declared_weight >= 0)
);

create table cargo_places (
  id uuid primary key,
  order_id uuid not null references orders(id),
  place_number integer not null check (place_number > 0),
  place_count_at_creation integer not null check (place_count_at_creation > 0),
  human_label text not null unique,
  status text not null default 'created'
    check (status in ('created', 'ready_for_loading', 'loaded', 'in_transit', 'unloaded', 'delivered', 'cancelled')),
  current_location_kind text not null default 'branch'
    check (current_location_kind in ('branch', 'vehicle', 'customer', 'unknown')),
  current_location_label text,
  current_branch_id uuid references branches(id),
  current_vehicle_id uuid references vehicles(id),
  current_trip_id uuid references trips(id),
  current_measurement_id uuid,
  version integer not null default 1 check (version > 0),
  created_by_command_id uuid not null references command_requests(id),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (order_id, place_number),
  check (place_number <= place_count_at_creation),
  check (
    (current_location_kind = 'branch' and current_branch_id is not null and current_vehicle_id is null)
    or (current_location_kind = 'vehicle' and current_vehicle_id is not null and current_branch_id is null)
    or (current_location_kind in ('customer', 'unknown') and current_branch_id is null and current_vehicle_id is null)
  )
);

comment on column cargo_places.id is 'Stable opaque PlaceID (UUIDv7); never reuse or encode mutable cargo attributes.';
comment on column cargo_places.human_label is 'Human-readable alias printed beside the barcode; not the primary identifier.';
comment on column cargo_places.place_count_at_creation is 'Immutable N used by the printed n/N label at creation time.';

create table cargo_item_places (
  cargo_item_id uuid not null references cargo_items(id),
  cargo_place_id uuid not null references cargo_places(id),
  quantity numeric(14,3) not null default 1 check (quantity > 0),
  primary key (cargo_item_id, cargo_place_id)
);

create table cargo_place_measurements (
  id uuid primary key,
  cargo_place_id uuid not null references cargo_places(id),
  command_id uuid not null references command_requests(id),
  supersedes_measurement_id uuid,
  dimension_state text not null
    check (dimension_state in ('complete', 'partial', 'unknown', 'not_measurable')),
  length numeric(14,3) check (length > 0),
  width numeric(14,3) check (width > 0),
  height numeric(14,3) check (height > 0),
  dimension_unit text not null default 'cm' check (dimension_unit in ('cm', 'in')),
  weight numeric(14,3) check (weight >= 0),
  weight_unit text not null default 'kg' check (weight_unit in ('kg', 'lb')),
  weight_source text not null
    check (weight_source in ('measured', 'declared', 'allocated', 'estimated', 'corrected', 'unknown')),
  unknown_reason text,
  measured_by_user_id uuid not null references app_users(id),
  measured_at timestamptz not null,
  received_at timestamptz not null default now(),
  note text,
  unique (cargo_place_id, command_id),
  unique (id, cargo_place_id),
  foreign key (supersedes_measurement_id, cargo_place_id)
    references cargo_place_measurements(id, cargo_place_id),
  check (
    (dimension_state = 'complete' and length is not null and width is not null and height is not null)
    or
    (dimension_state = 'partial'
      and num_nonnulls(length, width, height) between 1 and 2)
    or
    (dimension_state in ('unknown', 'not_measurable')
      and length is null and width is null and height is null)
  ),
  check (
    (weight_source = 'unknown' and weight is null)
    or
    (weight_source <> 'unknown' and weight is not null)
  ),
  check (
    (dimension_state = 'complete' and weight_source <> 'unknown')
    or length(trim(coalesce(unknown_reason, ''))) > 0
  )
);

comment on column cargo_place_measurements.dimension_state is 'PD-011 quality state for independently complete, partial, unknown or not-measurable dimensions.';
comment on column cargo_place_measurements.unknown_reason is 'Required when dimensions or weight are incomplete/unknown; never replace missing values with zero.';

alter table cargo_places
  add constraint cargo_places_current_measurement_fk
  foreign key (current_measurement_id, id)
  references cargo_place_measurements(id, cargo_place_id);

create table place_label_aliases (
  id uuid primary key,
  cargo_place_id uuid not null references cargo_places(id),
  label_code text not null unique,
  barcode_payload text not null unique,
  barcode_format_version smallint not null default 1 check (barcode_format_version > 0),
  status text not null default 'active' check (status in ('active', 'replaced', 'void')),
  printed_by_user_id uuid references app_users(id),
  printed_at timestamptz,
  replaced_by_label_id uuid references place_label_aliases(id),
  created_by_command_id uuid not null references command_requests(id),
  created_at timestamptz not null default now(),
  check ((status = 'replaced') = (replaced_by_label_id is not null)),
  check (replaced_by_label_id is null or replaced_by_label_id <> id)
);

comment on column place_label_aliases.barcode_payload is 'Version marker plus opaque PlaceID only; mutable dimensions/status are forbidden.';

create table operation_places (
  work_operation_id uuid not null references work_operations(id),
  cargo_place_id uuid not null references cargo_places(id),
  outcome text not null
    check (outcome in ('expected', 'scanned', 'confirmed', 'missing', 'extra', 'damaged', 'rejected')),
  first_scanned_at timestamptz,
  confirmed_at timestamptz,
  note text,
  primary key (work_operation_id, cargo_place_id)
);

create table place_events (
  id uuid primary key,
  command_id uuid not null references command_requests(id),
  command_sequence integer not null default 1 check (command_sequence > 0),
  cargo_place_id uuid not null references cargo_places(id),
  work_operation_id uuid references work_operations(id),
  task_id uuid references tasks(id),
  trip_id uuid references trips(id),
  event_type text not null check (event_type in (
    'place_created', 'measurement_recorded', 'label_generated', 'label_printed', 'label_replaced',
    'pickup_completed', 'pickup_reversed', 'trip_assigned', 'loaded',
    'loading_reversed', 'unloaded', 'unloading_reversed',
    'dropoff_completed', 'dropoff_reversed', 'damage_reported', 'location_changed'
  )),
  entity_version integer not null check (entity_version > 0),
  actor_user_id uuid not null references app_users(id),
  device_id uuid references devices(id),
  branch_id uuid not null references branches(id),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  source text not null default 'mobile'
    check (source in ('mobile', 'api', 'integration', 'admin')),
  reason text,
  payload jsonb not null default '{}'::jsonb,
  unique (command_id, command_sequence),
  unique (cargo_place_id, entity_version)
);

comment on table place_events is 'Immutable business fact stream. Corrections are compensating events, never updates.';

create table manifest_versions (
  id uuid primary key,
  trip_id uuid not null references trips(id),
  version integer not null check (version > 0),
  manifest_type text not null
    check (manifest_type in ('expected', 'confirmed_loading', 'confirmed_unloading')),
  status text not null default 'draft'
    check (status in ('draft', 'confirmed', 'superseded')),
  source_version_id uuid,
  created_by_user_id uuid not null references app_users(id),
  created_by_command_id uuid references command_requests(id),
  confirmed_by_user_id uuid references app_users(id),
  created_at timestamptz not null default now(),
  confirmed_at timestamptz,
  totals_snapshot jsonb not null default '{}'::jsonb,
  unique (trip_id, version),
  unique (id, trip_id),
  foreign key (source_version_id, trip_id) references manifest_versions(id, trip_id),
  check ((status = 'draft') = (confirmed_at is null)),
  check (source_version_id is null or source_version_id <> id)
);

create table manifest_places (
  manifest_version_id uuid not null references manifest_versions(id),
  cargo_place_id uuid not null references cargo_places(id),
  sequence_number integer not null check (sequence_number > 0),
  outcome text not null default 'expected'
    check (outcome in ('expected', 'confirmed', 'missing', 'extra', 'damaged', 'rejected')),
  dimensions_snapshot jsonb not null default '{}'::jsonb,
  weight_snapshot numeric(14,3),
  weight_unit text check (weight_unit in ('kg', 'lb')),
  weight_source text,
  label_snapshot text not null,
  status_snapshot text not null,
  location_snapshot text,
  primary key (manifest_version_id, cargo_place_id),
  unique (manifest_version_id, sequence_number),
  check (weight_snapshot is null or weight_snapshot >= 0),
  check ((weight_snapshot is null) = (weight_unit is null))
);

alter table trips
  add constraint trips_loading_manifest_fk
  foreign key (confirmed_loading_manifest_id, id) references manifest_versions(id, trip_id),
  add constraint trips_unloading_manifest_fk
  foreign key (confirmed_unloading_manifest_id, id) references manifest_versions(id, trip_id),
  add constraint trips_manifest_ids_differ_ck
  check (
    confirmed_loading_manifest_id is null
    or confirmed_unloading_manifest_id is null
    or confirmed_loading_manifest_id <> confirmed_unloading_manifest_id
  );

create table discrepancies (
  id uuid primary key,
  branch_id uuid not null references branches(id),
  order_id uuid references orders(id),
  trip_id uuid references trips(id),
  cargo_place_id uuid references cargo_places(id),
  work_operation_id uuid not null references work_operations(id),
  discrepancy_type text not null check (discrepancy_type in (
    'missing', 'extra', 'damaged', 'wrong_trip', 'unknown_code', 'measurement_mismatch', 'other'
  )),
  severity text not null default 'medium' check (severity in ('low', 'medium', 'high', 'critical')),
  status text not null default 'open'
    check (status in ('open', 'needs_review', 'resolved', 'dismissed')),
  description text,
  resolution text,
  owner_user_id uuid references app_users(id),
  due_at timestamptz,
  resolved_at timestamptz,
  version integer not null default 1 check (version > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (order_id is not null or trip_id is not null),
  check ((status in ('resolved', 'dismissed')) = (resolved_at is not null))
);

create table discrepancy_events (
  id uuid primary key,
  discrepancy_id uuid not null references discrepancies(id),
  command_id uuid not null references command_requests(id),
  event_type text not null
    check (event_type in ('created', 'assigned', 'commented', 'evidence_added', 'resolved', 'dismissed', 'reopened')),
  actor_user_id uuid not null references app_users(id),
  occurred_at timestamptz not null,
  received_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  unique (discrepancy_id, command_id, event_type)
);

create table media_objects (
  id uuid primary key,
  branch_id uuid not null references branches(id),
  storage_provider text not null default 's3',
  bucket text not null,
  object_key text not null,
  mime_type text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  checksum_sha256 text not null check (checksum_sha256 ~ '^[0-9a-f]{64}$'),
  status text not null default 'pending_upload'
    check (status in ('pending_upload', 'available', 'quarantined', 'deleted')),
  captured_by_user_id uuid references app_users(id),
  captured_by_device_id uuid references devices(id),
  captured_at timestamptz,
  uploaded_at timestamptz,
  retention_until timestamptz,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (storage_provider, bucket, object_key),
  check (uploaded_at is null or status <> 'pending_upload')
);

comment on table media_objects is 'Only file metadata is stored in PostgreSQL; binary data lives in object storage.';

create table documents (
  id uuid primary key,
  branch_id uuid not null references branches(id),
  document_type text not null check (document_type in ('order_ebol', 'interstate_bol', 'external_document')),
  order_id uuid references orders(id),
  trip_id uuid references trips(id),
  document_number text,
  status text not null default 'draft' check (status in ('draft', 'issued', 'void')),
  current_version_id uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (
    (order_id is not null and trip_id is null)
    or (order_id is null and trip_id is not null)
  ),
  check (
    (document_type = 'order_ebol' and order_id is not null)
    or (document_type = 'interstate_bol' and trip_id is not null)
    or document_type = 'external_document'
  )
);

create unique index documents_number_uq
  on documents (document_number)
  where document_number is not null;

create table document_versions (
  id uuid primary key,
  document_id uuid not null references documents(id),
  version integer not null check (version > 0),
  status text not null default 'draft'
    check (status in ('draft', 'generated', 'issued', 'void')),
  render_purpose text not null
    check (render_purpose in ('pickup', 'delivery', 'pod', 'interstate_bol', 'external_copy')),
  source_manifest_version_id uuid references manifest_versions(id),
  source_snapshot jsonb not null,
  pdf_media_id uuid references media_objects(id),
  checksum_sha256 text check (checksum_sha256 is null or checksum_sha256 ~ '^[0-9a-f]{64}$'),
  correction_reason text,
  created_by_user_id uuid not null references app_users(id),
  created_at timestamptz not null default now(),
  generated_at timestamptz,
  issued_at timestamptz,
  unique (document_id, version),
  unique (id, document_id),
  check ((pdf_media_id is null) = (checksum_sha256 is null)),
  check (issued_at is null or generated_at is not null),
  check (status <> 'issued' or issued_at is not null)
);

alter table documents
  add constraint documents_current_version_fk
  foreign key (current_version_id, id) references document_versions(id, document_id);

create table signatures (
  id uuid primary key,
  signer_role text not null check (signer_role in ('driver', 'shipper', 'consignee', 'warehouse', 'supervisor')),
  signer_name text not null,
  signed_at timestamptz not null,
  signature_media_id uuid references media_objects(id),
  attestation jsonb not null default '{}'::jsonb,
  captured_by_user_id uuid not null references app_users(id),
  created_at timestamptz not null default now()
);

create table document_signatures (
  document_version_id uuid not null references document_versions(id),
  signature_id uuid not null references signatures(id),
  phase text not null check (phase in ('pickup', 'delivery', 'loading', 'unloading')),
  primary key (document_version_id, signature_id)
);

create table document_snapshots (
  id uuid primary key,
  document_version_id uuid not null references document_versions(id),
  phase text not null check (phase in ('pickup', 'delivery', 'loading', 'unloading')),
  work_operation_id uuid references work_operations(id),
  captured_at timestamptz not null,
  snapshot jsonb not null,
  unique (document_version_id, phase)
);

create table order_media (
  order_id uuid not null references orders(id),
  media_id uuid not null references media_objects(id),
  purpose text not null check (purpose in ('attachment', 'external_document', 'damage_evidence', 'other')),
  primary key (order_id, media_id)
);

create table cargo_place_media (
  cargo_place_id uuid not null references cargo_places(id),
  media_id uuid not null references media_objects(id),
  purpose text not null check (purpose in ('cargo_photo', 'label_photo', 'damage_evidence', 'other')),
  primary key (cargo_place_id, media_id)
);

create table work_operation_media (
  work_operation_id uuid not null references work_operations(id),
  media_id uuid not null references media_objects(id),
  purpose text not null check (purpose in ('evidence', 'signature_context', 'other')),
  primary key (work_operation_id, media_id)
);

create table document_version_media (
  document_version_id uuid not null references document_versions(id),
  media_id uuid not null references media_objects(id),
  purpose text not null check (purpose in ('source', 'rendered_pdf', 'attachment')),
  primary key (document_version_id, media_id)
);

-- Mapping boundary for TMS/ERP/DMS identifiers. local_id validity is enforced by
-- the integration service because one polymorphic FK cannot be expressed safely.
create table integration_entity_links (
  id uuid primary key,
  system_code text not null,
  entity_type text not null check (entity_type in ('order', 'task', 'route_run', 'trip', 'vehicle', 'document')),
  local_id uuid not null,
  external_id text not null,
  external_version text,
  last_synced_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (system_code, entity_type, external_id),
  unique (system_code, entity_type, local_id)
);

create table integration_attempts (
  id bigint generated always as identity primary key,
  system_code text not null,
  direction text not null check (direction in ('inbound', 'outbound')),
  entity_type text not null,
  entity_id uuid,
  command_id uuid references command_requests(id),
  status text not null check (status in ('started', 'succeeded', 'retry', 'failed', 'rejected')),
  attempt_number integer not null default 1 check (attempt_number > 0),
  request_summary jsonb not null default '{}'::jsonb,
  response_summary jsonb,
  error_code text,
  error_message text,
  started_at timestamptz not null default now(),
  completed_at timestamptz,
  next_retry_at timestamptz,
  check (completed_at is null or completed_at >= started_at)
);

create table outbox_messages (
  id bigint generated always as identity primary key,
  aggregate_type text not null,
  aggregate_id uuid not null,
  event_type text not null,
  payload jsonb not null,
  status text not null default 'pending'
    check (status in ('pending', 'processing', 'retry', 'published', 'dead_letter')),
  attempts integer not null default 0 check (attempts >= 0),
  available_at timestamptz not null default now(),
  locked_at timestamptz,
  published_at timestamptz,
  last_error text,
  created_at timestamptz not null default now()
);

create table device_sync_checkpoints (
  device_id uuid primary key references devices(id),
  last_outbox_id bigint not null default 0 check (last_outbox_id >= 0),
  last_successful_sync_at timestamptz,
  updated_at timestamptz not null default now()
);

create table audit_log (
  id bigint generated always as identity primary key,
  branch_id uuid references branches(id),
  actor_user_id uuid references app_users(id),
  device_id uuid references devices(id),
  action text not null,
  entity_type text not null,
  entity_id uuid,
  occurred_at timestamptz not null default now(),
  ip_address inet,
  metadata jsonb not null default '{}'::jsonb
);

-- Foreign-key and read-model indexes. PostgreSQL does not create FK indexes automatically.
create index devices_user_idx on devices (user_id);
create index devices_branch_idx on devices (branch_id) where branch_id is not null;
create index user_branch_roles_branch_idx on user_branch_roles (branch_id, user_id);
create index route_runs_branch_date_idx on route_runs (branch_id, service_date desc);
create index orders_origin_status_idx on orders (origin_branch_id, status) where origin_branch_id is not null;
create index orders_destination_status_idx on orders (destination_branch_id, status) where destination_branch_id is not null;
create index orders_movement_status_idx on orders (movement_type, status);
create index tasks_branch_status_schedule_idx on tasks (branch_id, status, scheduled_at);
create index tasks_order_idx on tasks (order_id);
create index tasks_route_run_idx on tasks (route_run_id, route_sequence) where route_run_id is not null;
create index trips_origin_status_idx on trips (origin_branch_id, status);
create index trips_destination_status_idx on trips (destination_branch_id, status);
create index trips_vehicle_idx on trips (vehicle_id) where vehicle_id is not null;
create index command_requests_device_received_idx on command_requests (device_id, received_at desc) where device_id is not null;
create index command_requests_pending_idx on command_requests (received_at) where status in ('received', 'retry');
create index command_requests_entity_idx on command_requests (entity_type, entity_id) where entity_id is not null;
create index work_operations_branch_status_idx on work_operations (branch_id, status, started_at desc);
create index work_operations_task_idx on work_operations (task_id) where task_id is not null;
create index work_operations_trip_idx on work_operations (trip_id) where trip_id is not null;
create index cargo_places_branch_status_idx on cargo_places (current_branch_id, status) where current_branch_id is not null;
create index cargo_places_trip_status_idx on cargo_places (current_trip_id, status) where current_trip_id is not null;
create index cargo_places_vehicle_idx on cargo_places (current_vehicle_id) where current_vehicle_id is not null;
create index cargo_item_places_place_idx on cargo_item_places (cargo_place_id);
create index cargo_place_measurements_place_time_idx on cargo_place_measurements (cargo_place_id, measured_at desc);
create index place_label_aliases_place_idx on place_label_aliases (cargo_place_id, status);
create index operation_places_place_idx on operation_places (cargo_place_id);
create index place_events_place_history_idx on place_events (cargo_place_id, occurred_at desc, received_at desc);
create index place_events_operation_idx on place_events (work_operation_id) where work_operation_id is not null;
create index place_events_task_idx on place_events (task_id) where task_id is not null;
create index place_events_trip_idx on place_events (trip_id) where trip_id is not null;
create index place_events_branch_time_idx on place_events (branch_id, occurred_at desc);
create index place_events_actor_branch_idx on place_events (actor_user_id, branch_id);
create index manifest_places_place_idx on manifest_places (cargo_place_id);
create index discrepancies_open_idx on discrepancies (branch_id, severity, created_at) where status in ('open', 'needs_review');
create index discrepancies_place_idx on discrepancies (cargo_place_id) where cargo_place_id is not null;
create index discrepancies_operation_idx on discrepancies (work_operation_id);
create index discrepancy_events_history_idx on discrepancy_events (discrepancy_id, occurred_at);
create index media_objects_branch_status_idx on media_objects (branch_id, status, created_at desc);
create index media_objects_checksum_idx on media_objects (storage_provider, bucket, checksum_sha256);
create index documents_order_idx on documents (order_id) where order_id is not null;
create index documents_trip_idx on documents (trip_id) where trip_id is not null;
create index documents_branch_status_idx on documents (branch_id, status);
create index document_versions_manifest_idx on document_versions (source_manifest_version_id) where source_manifest_version_id is not null;
create index signatures_media_idx on signatures (signature_media_id) where signature_media_id is not null;
create index document_signatures_signature_idx on document_signatures (signature_id);
create index order_media_media_idx on order_media (media_id);
create index cargo_place_media_media_idx on cargo_place_media (media_id);
create index work_operation_media_media_idx on work_operation_media (media_id);
create index document_version_media_media_idx on document_version_media (media_id);
create index integration_links_local_idx on integration_entity_links (entity_type, local_id);
create index integration_attempts_retry_idx on integration_attempts (next_retry_at) where status = 'retry';
create index outbox_ready_idx on outbox_messages (available_at, id) where status in ('pending', 'retry');
create index audit_log_entity_idx on audit_log (entity_type, entity_id, occurred_at desc) where entity_id is not null;
create index audit_log_actor_idx on audit_log (actor_user_id, occurred_at desc) where actor_user_id is not null;

create trigger branches_touch_updated_at before update on branches
  for each row execute function touch_updated_at();
create trigger app_users_touch_updated_at before update on app_users
  for each row execute function touch_updated_at();
create trigger devices_touch_updated_at before update on devices
  for each row execute function touch_updated_at();
create trigger route_runs_touch_updated_at before update on route_runs
  for each row execute function touch_updated_at();
create trigger orders_touch_updated_at before update on orders
  for each row execute function touch_updated_at();
create trigger tasks_touch_updated_at before update on tasks
  for each row execute function touch_updated_at();
create trigger vehicles_touch_updated_at before update on vehicles
  for each row execute function touch_updated_at();
create trigger trips_touch_updated_at before update on trips
  for each row execute function touch_updated_at();
create trigger work_operations_touch_updated_at before update on work_operations
  for each row execute function touch_updated_at();
create trigger cargo_items_touch_updated_at before update on cargo_items
  for each row execute function touch_updated_at();
create trigger cargo_places_touch_updated_at before update on cargo_places
  for each row execute function touch_updated_at();
create trigger discrepancies_touch_updated_at before update on discrepancies
  for each row execute function touch_updated_at();
create trigger media_objects_touch_updated_at before update on media_objects
  for each row execute function touch_updated_at();
create trigger documents_touch_updated_at before update on documents
  for each row execute function touch_updated_at();
create trigger integration_links_touch_updated_at before update on integration_entity_links
  for each row execute function touch_updated_at();
create trigger device_sync_touch_updated_at before update on device_sync_checkpoints
  for each row execute function touch_updated_at();

create trigger place_events_append_only
  before update or delete on place_events
  for each row execute function reject_append_only_mutation();
create trigger measurements_append_only
  before update or delete on cargo_place_measurements
  for each row execute function reject_append_only_mutation();
create trigger discrepancy_events_append_only
  before update or delete on discrepancy_events
  for each row execute function reject_append_only_mutation();
create trigger document_snapshots_append_only
  before update or delete on document_snapshots
  for each row execute function reject_append_only_mutation();
create trigger signatures_append_only
  before update or delete on signatures
  for each row execute function reject_append_only_mutation();
create trigger audit_log_append_only
  before update or delete on audit_log
  for each row execute function reject_append_only_mutation();

create function guard_manifest_place_mutation()
returns trigger
language plpgsql
as $$
declare
  target_manifest_id uuid;
  target_status text;
begin
  if tg_op = 'DELETE' then
    target_manifest_id := old.manifest_version_id;
  else
    target_manifest_id := new.manifest_version_id;
  end if;
  select status into target_status from manifest_versions where id = target_manifest_id;
  if target_status <> 'draft' then
    raise exception 'Manifest % is % and immutable', target_manifest_id, target_status;
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger manifest_places_draft_only
  before insert or update or delete on manifest_places
  for each row execute function guard_manifest_place_mutation();

create function guard_locked_manifest_version()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('confirmed', 'superseded') then
    raise exception 'Confirmed/superseded manifest versions are immutable';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger manifest_versions_lock
  before update or delete on manifest_versions
  for each row execute function guard_locked_manifest_version();

create function guard_issued_document_version()
returns trigger
language plpgsql
as $$
begin
  if old.status in ('issued', 'void') then
    raise exception 'Issued/void document versions are immutable; create a new version';
  end if;
  if tg_op = 'DELETE' then
    return old;
  end if;
  return new;
end;
$$;

create trigger document_versions_lock
  before update or delete on document_versions
  for each row execute function guard_issued_document_version();

create view cargo_place_current_v with (security_invoker = true) as
select
  p.id as place_id,
  p.human_label,
  p.order_id,
  o.order_number,
  p.place_number,
  p.place_count_at_creation as total_places,
  p.status,
  p.current_location_kind,
  p.current_location_label,
  p.current_branch_id,
  b.name as current_branch_name,
  p.current_vehicle_id,
  v.vehicle_number,
  p.current_trip_id,
  t.trip_number,
  m.length,
  m.width,
  m.height,
  m.dimension_state,
  m.dimension_unit,
  m.weight,
  m.weight_unit,
  m.weight_source,
  m.unknown_reason,
  p.version,
  p.updated_at
from cargo_places p
join orders o on o.id = p.order_id
left join cargo_place_measurements m on m.id = p.current_measurement_id
left join branches b on b.id = p.current_branch_id
left join vehicles v on v.id = p.current_vehicle_id
left join trips t on t.id = p.current_trip_id;

create view cargo_place_history_v with (security_invoker = true) as
select
  e.cargo_place_id as place_id,
  e.id as event_id,
  e.event_type,
  e.entity_version,
  e.occurred_at,
  e.received_at,
  e.actor_user_id,
  u.display_name as actor_name,
  e.branch_id,
  b.name as branch_name,
  e.task_id,
  e.trip_id,
  e.reason,
  e.payload
from place_events e
join app_users u on u.id = e.actor_user_id
join branches b on b.id = e.branch_id;

revoke all on schema zaberman from public;
revoke all on all tables in schema zaberman from public;
revoke all on all sequences in schema zaberman from public;
revoke all on all functions in schema zaberman from public;

commit;
